### PR TITLE
Dynamic config for localhost and heroku

### PR DESCRIPTION
**Pull request by dlively1**
Hey,

Don't know if you want to pull any of this in, figure I would ask. Great app by the way, loved this switching from workbench.

I just switched the view engine to pass in the environment data so you don't have to switch the variables for clientID and callback. You can just have a .env on local with the info and the heroku configs for production.

I also removed node modules (hence all of the file changes). If you would be interested in pulling this let me know and I could clean it up if you don't want to remove node_modules directory. I just typically ignore them in projects.

### CODE REVIEW

**Comment by JitendraZaa** [comment]
Thanks Dan, for making app more configurable. I would like to pull up your modifications, please let me know next step...

**Comment by dlively1** [comment]
Let me add some details in the readme file on setting it up to be ran on local and heroku.

**Comment by dlively1** [comment]
Alright, added some info to the ReadMe file and an example .env file for running it locally with foreman (included in Heroku toolkit). Try it out and let me know, note my branch wipes out the node_modules so make sure you npm install to fetch all the dependencies.

Once again, awesome app the checkbox for field selection is great compared to workbench.

**Comment by JitendraZaa** [comment]
Thanks Dan, I will test it on my system and update with your code.

**Pull request merged**
